name: aveds_test
description: "Aaveds Test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.4.0
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true

